import argparse
import os

import gdown

URLS = {
    "checkpoints": {
        "ViT-B-32": "1YEBusuYj2J9tPyw1tWXHNXZcGpwjmG6f",
        "ViT-B-16": "1dVuJjwKSSCcRLrLwGoR5Pvm1ra9spg13",
        "ViT-L-14": "10DyLk0jvPB0O-ffU2x1_FGQ2DNJ-_-PY",
        'roberta-base': '1WfW5oX6ZoPtFTnfiYF9qxvb07kZIzEhc',
        'roberta-large': '1RH1sctFHiX3TSAcYXmEddOPyLqGjdX9Q'
    },
    "tall_masks": {
        "ViT-B-32": "1jpqsurrAdD5bn9i7pRBsTq4E3ayPb0YK",
        "ViT-B-16": "1jYNsdeFz6vlwIl5s4T48zeTm7FdwTSL9",
        "ViT-L-14": "16GVDMhpScmM3zeyfubjmNRFLiFKkBE7p",
    },
}

parser = argparse.ArgumentParser("Download checkpoints for Vision Transformer models")
parser.add_argument(
    "--model",
    type=str,
    required=True,
    help="Model type to download",
    choices=["ViT-B-32", "ViT-B-16", "ViT-L-14", 'roberta-base', 'roberta-large'],
)

parser.add_argument(
    "--type",
    type=str,
    required=True,
    help="Saved directory name",
    choices=["vit", "lm"],
)

parser.add_argument(
    "--kind",
    type=str,
    required=True,
    help="Kind of download: checkpoints refer to single-task fine-tuned models and tall_masks for the per-task binary"
    + " masks generated by the 'TALL-masks' method.",
    choices=["checkpoints", "tall_masks"],
)


if __name__ == "__main__":
    args = parser.parse_args()
    dir_path = f'../data/models/{args.type}'
    url = URLS[args.kind][args.model]
    url = "https://drive.google.com/drive/u/1/folders/" + url
    gdown.download_folder(url, output=os.path.join(dir_path, args.kind, args.model), quiet=False)

# how to use: 
# python download_checkpoints.py --model 'ViT-L-14' --type 'vit' --kind 'checkpoints'
# python download_checkpoints.py --model 'roberta-base' --type 'lm' --kind 'checkpoints'